{
  "swagger": "2.0",
  "info": {
    "title": "API Title",
    "version": "1.0"
  },
  "paths": {
    "/cpeinfo/{msisdn}": {
        "get": {
          "operationId": "getCpeInfo",
          "parameters": [{
            "name": "msisdn",
            "in": "path",
            "required": true,
            "type": "string"
          }],
        "description" : "returns cpe info based on msisdn",
        "responses": {
          "200": {
            "description": "cpe parameters",
            "schema": {
                "$ref": "#/definitions/CpeInfo"
            }
          }
        }
      }
    } 
  },
  "definitions": {
    "CpeInfo": {
      "type": "object",
      "properties": {
        "msisdn": {
          "type": "string"
        },
        "cpemodel": {
          "type": "string"
        },
        "cpeversion": {
          "type": "string"
        }
      }
    }
  }
}